package com.epam.jconference.model.enums;

public enum ErrorType {
    VALIDATION_ERROR_TYPE,
    UNAUTHORIZED_ACCESS_ERROR_TYPE,
    PROCESSING_ERROR_TYPE,
    DATABASE_ERROR_TYPE,
    FATAL_ERROR_TYPE,
    INVALID_DATA_ERROR_TYPE
}
